fix: use command -v in 1-ubuntu-debugger

diff --git a/1-ubuntu-debugger/Dockerfile b/1-ubuntu-debugger/Dockerfile
--- a/1-ubuntu-debugger/Dockerfile
+++ b/1-ubuntu-debugger/Dockerfile
@@ -12,7 +12,7 @@ RUN cat /etc/os-release
 #       Add RUN command(s) to apt-get install 'curl' and 'dnsutils' packages.
 
 # Check if the commands are available now
-RUN command curl || command nslookup || echo "Network utils NOT found!"
+RUN command -v curl || command -v nslookup || echo "Network utils NOT found!"
 
 # We don't need to be root anymore,
 # switch to Ubuntu's builtin unpriviledged user.
